In [10]:
data = {
    "height": [1.4,1.2,1.0,1.5,1.8],
    "fav-movie": ["baby days out", "the original", "pirates of the carrebean", "tom and jerry","wednesday"],
    
}

In [11]:
import pandas as pd
df = pd.DataFrame(data)

In [12]:
df

   height                 fav-movie
0     1.4             baby days out
1     1.2              the original
2     1.0  pirates of the carrebean
3     1.5             tom and jerry
4     1.8                 wednesday

## Label Encoding

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:


# 1. Sample dataset
#df = pd.DataFrame({'Target_Class': ['Low', 'High', 'Medium', 'Low', 'High']})

# 2. Initialize the LabelEncoder
le = LabelEncoder()

# 3. Fit to the column and transform text to integers
df['Encoded_Class']=le.fit_transform(df['fav-movie'])
print(df)

   height                 fav-movie  Encoded_Class
0     1.4             baby days out              0
1     1.2              the original              2
2     1.0  pirates of the carrebean              1
3     1.5             tom and jerry              3
4     1.8                 wednesday              4

## One Hot Encoding

In [18]:
#import pandas as pd

# 1. Create a sample dataset with a nominal categorical columndata = {'City': ['Paris', 'New York', 'Tokyo', 'Paris', 'Tokyo']}

#df = pd.DataFrame(data)

# 2. Apply one-hot encoding and fix the dummy variable trap
# 'drop_first=True' removes the very first category column (alphabetically)
# 'dtype=int' changes the output from True/False booleans to 1/0 integers

df_encoded = pd.get_dummies(df, columns=['fav-movie'], drop_first=True, dtype=int)
# Print the resulting dataframe
df_encoded
#,

,height,Encoded_Class,fav-movie_pirates of the carrebean,fav-movie_the original,fav-movie_tom and jerry,fav-movie_wednesday
0,1.4,0,0,0,0,0
1,1.2,2,0,1,0,0
2,1.0,1,1,0,0,0
3,1.5,3,0,0,1,0
4,1.8,4,0,0,0,1

## Bag of Words

In [24]:


from sklearn.feature_extraction.text import CountVectorizer

# 1. Create a sample dataset with text reviews
data = {'reviews': ['the food is good',
                           'New food is terrible',
                           'good food and good services']
              }

df = pd.DataFrame(data)

# 2. Initialize the CountVectorizer
# stop_words='english' removes useless words like 'the' and 'and' to save memory
vectorizer = CountVectorizer(stop_words='english')

# 3. Fit and transform the text column 
# This learns the unique vocabulary and counts the word occurrences 
bow_matrix = vectorizer.fit_transform(df['reviews'])

# 4. Convert the matrix into a clean Pandas DataFrame
# vectorizer.get_feature_names_out() extracts the learned vocabulary as column names 

df_bow = pd.DataFrame(bow_matrix.toarray(),columns=vectorizer.get_feature_names_out()) 

df_bow

   food  good  new  services  terrible
0     1     1    0         0         0
1     1     0    1         0         1
2     1     2    0         1         0

## Word Embeddings

<h5>Tokenizers</h5>

In [25]:
text = "Deep learning is amazing!"
tokens = text.split()
print(tokens)

['Deep', 'learning', 'is', 'amazing!']

In [26]:
text = "Deep learning is amazing!"
tokens = text.split('e')
print(tokens)

['D', '', 'p l', 'arning is amazing!']

<h5>2. word-level tokenization that handles punctuation</h5>

In [28]:
import re
#re helps find patterns like the structure of an email

text = "Deep learning is amazing!"
tokens =re.findall(r"\w+|[^\s]",text)
print(tokens)

['Deep', 'learning', 'is', 'amazing', '!']

<h5>3.Charater-Level Tokenization</h5>

In [29]:
character_token = list(text)
print(character_token)

['D', 'e', 'e', 'p', ' ', 'l', 'e', 'a', 'r', 'n', 'i', 'n', 'g', ' ', 'i', 's', ' ', 'a', 'm', 'a', 'z', 'i', 'n', 'g', '!']

In [36]:
with open ("raw.txt","r", encoding="utf-8") as f:
    raw_text = f.read()
len(raw_text), raw_text

(228,
 'Grace is very @@beautiful and hard working. \nI like the ###way she carries herself.\nBeauty in Bl---ack deserves the hype. \nIt is very in@@teresting to watch. Everyhing is in place: from the acting, scenes and the video quality. ')

<h5>2. text cleaning using regular expressions</h5>

In [48]:
import re
white_space_splittx = re.split(r'\s', raw_text)
print(white_space_splittx)

['Grace', 'is', 'very', '@@beautiful', 'and', 'hard', 'working.', '', 'I', 'like', 'the', '###way', 'she', 'carries', 'herself.', 'Beauty', 'in', 'Bl---ack', 'deserves', 'the', 'hype.', '', 'It', 'is', 'very', 'in@@teresting', 'to', 'watch.', 'Everyhing', 'is', 'in', 'place:', 'from', 'the', 'acting,', 'scenes', 'and', 'the', 'video', 'quality.', '']

In [57]:
raw_text = re.sub(r'@\w+', "",raw_text,flags=re.MULTILINE )
raw_text = re.sub(r'#\w+', "", raw_text,flags=re.MULTILINE)

#remove anything that is not alphabet
raw_text = re.sub(r'[^a-zA-Z\s]', '',raw_text)

#remove any white spaces
raw_text = re.sub(r'\s+', ' ', raw_text)
raw_text

'GraceisveryandhardworkingIliketheshecarriesherselfBeautyinBlackdeservesthehypeItisveryintowatchEveryhingisinplacefromtheactingscenesandthevideoquality'

In [55]:
#splitting using other criteria
white_space_splittx_with_special_xters = re.split(r'---|[@^!#*?&]|\s',raw_text)
print(white_space_splittx_with_special_xters)

['Grace', 'is', 'very', 'and', 'hard', 'working', 'I', 'like', 'the', 'she', 'carries', 'herself', 'Beauty', 'in', 'Black', 'deserves', 'the', 'hype', 'It', 'is', 'very', 'in', 'to', 'watch', 'Everyhing', 'is', 'in', 'place', 'from', 'the', 'acting', 'scenes', 'and', 'the', 'video', 'quality']

## Remove white spaces from splitted text

In [59]:
#hint: use list comprehension 
strip_text = [ word.strip() for word in white_space_splittx_with_special_xters if word.strip()]
len(strip_text)

36

## create token-IDs for these words

In [61]:
# sort the text
sorted_strip_text = sorted(set(strip_text))
print(sorted_strip_text)

['Beauty', 'Black', 'Everyhing', 'Grace', 'I', 'It', 'acting', 'and', 'carries', 'deserves', 'from', 'hard', 'herself', 'hype', 'in', 'is', 'like', 'place', 'quality', 'scenes', 'she', 'the', 'to', 'very', 'video', 'watch', 'working']

In [62]:
# enumerate takes in two variables and can out put them
for idx,token in enumerate(sorted_strip_text):
    print(f" {idx} : {token}")

 0 : Beauty
 1 : Black
 2 : Everyhing
 3 : Grace
 4 : I
 5 : It
 6 : acting
 7 : and
 8 : carries
 9 : deserves
 10 : from
 11 : hard
 12 : herself
 13 : hype
 14 : in
 15 : is
 16 : like
 17 : place
 18 : quality
 19 : scenes
 20 : she
 21 : the
 22 : to
 23 : very
 24 : video
 25 : watch
 26 : working

In [63]:
# Creating a vocabulary
vocabulary = {}
for idx,token in enumerate(sorted_strip_text):
    vocabulary[token] = idx
vocabulary

{'Beauty': 0,
 'Black': 1,
 'Everyhing': 2,
 'Grace': 3,
 'I': 4,
 'It': 5,
 'acting': 6,
 'and': 7,
 'carries': 8,
 'deserves': 9,
 'from': 10,
 'hard': 11,
 'herself': 12,
 'hype': 13,
 'in': 14,
 'is': 15,
 'like': 16,
 'place': 17,
 'quality': 18,
 'scenes': 19,
 'she': 20,
 'the': 21,
 'to': 22,
 'very': 23,
 'video': 24,
 'watch': 25,
 'working': 26}

In [68]:
# create id-to-string mapping
id_to_str = {}
for idx,token in enumerate(vocabulary):
    id_to_str[idx] = token
id_to_str

{0: 'Beauty',
 1: 'Black',
 2: 'Everyhing',
 3: 'Grace',
 4: 'I',
 5: 'It',
 6: 'acting',
 7: 'and',
 8: 'carries',
 9: 'deserves',
 10: 'from',
 11: 'hard',
 12: 'herself',
 13: 'hype',
 14: 'in',
 15: 'is',
 16: 'like',
 17: 'place',
 18: 'quality',
 19: 'scenes',
 20: 'she',
 21: 'the',
 22: 'to',
 23: 'very',
 24: 'video',
 25: 'watch',
 26: 'working'}

In [69]:
token_ids = [vocabulary[word] for word in strip_text]
print(token_ids)

[3, 15, 23, 7, 11, 26, 4, 16, 21, 20, 8, 12, 0, 14, 1, 9, 21, 13, 5, 15, 23, 14, 22, 25, 2, 15, 14, 17, 10, 21, 6, 19, 7, 21, 24, 18]

In [70]:
tokens_recovered = [id_to_str[idx] for idx in token_ids]
" ".join(tokens_recovered)

'Grace is very and hard working I like the she carries herself Beauty in Black deserves the hype It is very in to watch Everyhing is in place from the acting scenes and the video quality'